/* Windows/MSVC configuration for iperf 3.21.
 *
 * This file is normally generated by configure on POSIX systems.  Keep Windows
 * feature macros conservative and implement compatibility in windows/compat.
 */
#ifndef IPERF_CONFIG_H
#define IPERF_CONFIG_H

#define PACKAGE "iperf"
#define PACKAGE_NAME "iperf"
#define PACKAGE_TARNAME "iperf"
#define PACKAGE_VERSION "3.21"
#define PACKAGE_STRING "iperf 3.21"
#define PACKAGE_BUGREPORT "iperf@es.net"
#define PACKAGE_URL "https://software.es.net/iperf/"
#define VERSION "3.21"

#define HAVE_CLOCK_GETTIME 1
#define HAVE_DAEMON 1
#define HAVE_GETLINE 1
#define HAVE_INTTYPES_H 1
#define HAVE_PTHREAD 1
#define HAVE_SETPROCESSAFFINITYMASK 1
#define HAVE_SOCKET_SHUTDOWN_SHUT_WR 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STDATOMIC_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define STDC_HEADERS 1

#endif
